/* 
 * File:   mcal_interrupt_gen_cfg.h
 * Author: Amr Ali
 *
 * Created on September 11, 2023, 2:43 AM
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H
#define	MCAL_INTERRUPT_GEN_CFG_H

#define INTERRUPT_FEATURE_ENABLE 1
#define INTERRUPT_PERIRITY_LEVELS_ENABLE        INTERRUPT_FEATURE_ENABLE
#define EXTERNAL_INTERRUPT_INTx_FEATURE_ENABLE  INTERRUPT_FEATURE_ENABLE
#define EXTERNAL_INTERRUPT_ONCHANGE_FEATURE_ENABLE  INTERRUPT_FEATURE_ENABLE
#define ADC_INTERRUPT_FEATURE_ENADBLE INTERRUPT_FEATURE_ENABLE

#endif	/* MCAL_INTERRUPT_GEN_CFG_H */

